dist: trusty
sudo: false
language: c++

env:
  global:
  - COMPILER=g++

# Default --recursive (rapidjson/thirdparty/gtest) is unnecessary
git:
  submodules: false
  depth: 1

before_install:
  - git submodule update --init

# addons:
#   apt:
#     sources: &apt_sources
#       - ubuntu-toolchain-r-test
#       - llvm-toolchain-precise-3.5
#       #- llvm-toolchain-precise-3.6
#       #- llvm-toolchain-precise-3.7
#       #- llvm-toolchain-precise-3.8
#       #- llvm-toolchain-trusty-3.9
#       #- llvm-toolchain-trusty-4.0
#       - llvm-toolchain-trusty-5.0

cache:
  directories:
    - build/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-14.04/
    - build/clang+llvm-5.0.1-x86_64-apple-darwin/

matrix:
  # Don't wait for all builds to complete if one of the builds fails or the
  # only builds left that can fail are marked optional.
  fast_finish: true

  include:
    - env: COMPILER=g++5
      compiler: gcc
      os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-5"]

    - env: COMPILER=g++-7
      compiler: gcc
      os: linux
      addons:
        apt:
          sources: ["ubuntu-toolchain-r-test"]
          packages: ["g++-7"]

    - env: COMPILER=clang-3.5
      compiler: clang
      os: linux
      addons:
        apt:
          sources: ["llvm-toolchain-precise-3.5"]
          packages: ["clang-3.5"]

    - env: COMPILER=clang-5.0
      compiler: clang
      os: linux
      addons:
        apt:
          sources: ["llvm-toolchain-trusty-5.0"]
          packages: ["clang-5.0"]

    - env: COMPILER=clang++
      compiler: clang
      os: osx
      osx_image: xcode9.1

    - env: COMPILER=g++-7
      compiler: gcc
      os: osx
      osx_image: xcode9.1

  allow_failures:

    - env: COMPILER=g++-5
      compiler: gcc
      osx_image: xcode9.1
      os: osx

    - env: COMPILER=g++-7
      compiler: gcc
      osx_image: xcode9.1
      os: osx

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      if [[ "${COMPILER}" = "g++-5" ]]; then
        brew install gcc5
      fi
      if [[ "${COMPILER}" = "g++-7" ]]; then
        brew install gcc7
      fi
    fi

  - export CXX="${COMPILER}"

before_script:
  - ${CXX} --version

script:
  - travis_retry ./waf configure
  - ./waf build
  - ./build/release/bin/cquery --ci --log-all-to-stderr --test-unit
  - ./build/release/bin/cquery --ci --log-all-to-stderr --test-index

notifications:
  email: false
